export const COURSES_DATA = {
  investing: {
    modules: [
      { id:'inv-01', title:{fr:'Introduction à l\'investissement',en:'Introduction to Investing'},
        content:{
          fr:'<h2>Bienvenue dans le monde de l\'investissement</h2><p>L\'investissement est l\'art de faire travailler votre argent pour vous. Ce module introductif vous donnera les bases essentielles pour comprendre les marchés financiers et prendre vos premières décisions d\'investissement éclairées.</p><img src="https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?w=800&h=350&fit=crop&q=80" alt="Marchés financiers" style="width:100%;border-radius:12px;margin:20px 0"/><h3>Les 3 piliers de l\'investissement</h3><p><strong>1. Le rendement</strong> — C\'est le gain que vous espérez obtenir. Il peut prendre la forme de dividendes, d\'intérêts ou de plus-values.</p><p><strong>2. Le risque</strong> — Tout investissement comporte un risque de perte. Plus le rendement potentiel est élevé, plus le risque l\'est généralement aussi.</p><p><strong>3. La liquidité</strong> — La facilité avec laquelle vous pouvez convertir votre investissement en cash sans perte de valeur significative.</p><div style="background:#f0fdf4;border-left:4px solid #59A52C;padding:16px 20px;border-radius:0 12px 12px 0;margin:20px 0"><strong>💡 Règle d\'or :</strong> Ne jamais investir de l\'argent dont vous pourriez avoir besoin à court terme. L\'investissement est un marathon, pas un sprint.</div><h3>Types d\'actifs financiers</h3><p>Les principaux types d\'actifs sont :</p><p>• <strong>Actions</strong> : Parts de propriété dans une entreprise<br/>• <strong>Obligations</strong> : Prêts aux entreprises ou gouvernements<br/>• <strong>Immobilier</strong> : Investissement dans la pierre<br/>• <strong>Matières premières</strong> : Or, pétrole, etc.<br/>• <strong>Cryptomonnaies</strong> : Actifs numériques décentralisés</p><img src="https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&h=300&fit=crop&q=80" alt="Graphiques" style="width:100%;border-radius:12px;margin:20px 0"/>',
          en:'<h2>Welcome to the world of investing</h2><p>Investing is the art of making your money work for you. This introductory module will give you the essential foundations to understand financial markets and make your first informed investment decisions.</p><img src="https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?w=800&h=350&fit=crop&q=80" alt="Financial markets" style="width:100%;border-radius:12px;margin:20px 0"/><h3>The 3 pillars of investing</h3><p><strong>1. Return</strong> — The gain you expect to achieve. It can come as dividends, interest, or capital gains.</p><p><strong>2. Risk</strong> — Every investment carries risk of loss. The higher the potential return, the higher the risk typically is.</p><p><strong>3. Liquidity</strong> — How easily you can convert your investment to cash without significant loss in value.</p>'
        }},
      { id:'inv-02', title:{fr:'Les classes d\'actifs',en:'Asset Classes'},
        content:{
          fr:'<h2>Comprendre les classes d\'actifs</h2><p>Une classe d\'actifs est un ensemble d\'instruments financiers qui partagent des caractéristiques similaires et se comportent de manière comparable sur les marchés.</p><img src="https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=350&fit=crop&q=80" alt="Asset Classes" style="width:100%;border-radius:12px;margin:20px 0"/><h3>Actions (Equities)</h3><p>Acheter une action, c\'est devenir copropriétaire d\'une entreprise. Historiquement, les actions offrent les meilleurs rendements à long terme (~7-10% par an) mais avec une volatilité plus élevée.</p><div style="background:linear-gradient(135deg,#0f172a,#1e293b);color:#fff;padding:20px;border-radius:12px;margin:20px 0"><strong>📊 Performance historique S&P 500</strong><br/>Rendement annualisé moyen sur 30 ans : ~10.7%<br/>Pire année : -38.5% (2008) | Meilleure : +34.1% (1995)</div><h3>Obligations (Bonds)</h3><p>Les obligations sont des prêts que vous faites à un gouvernement ou une entreprise. Elles offrent des paiements d\'intérêts réguliers et sont généralement moins risquées que les actions.</p><h3>Matières premières</h3><p>L\'or, l\'argent, le pétrole... Les matières premières servent souvent de couverture contre l\'inflation et de diversification.</p>',
          en:'<h2>Understanding asset classes</h2><p>An asset class is a group of financial instruments that share similar characteristics and behave similarly in markets.</p>'
        }},
      { id:'inv-03', title:{fr:'Construction de portefeuille',en:'Portfolio Construction'},
        content:{fr:'<h2>Construire un portefeuille solide</h2><p>La construction de portefeuille est l\'art de combiner différents actifs pour optimiser le rapport rendement/risque.</p><img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=350&fit=crop&q=80" alt="Portfolio" style="width:100%;border-radius:12px;margin:20px 0"/><h3>La diversification</h3><p>Ne mettez pas tous vos œufs dans le même panier. La diversification réduit le risque sans nécessairement réduire le rendement attendu.</p><div style="background:#eff6ff;border-left:4px solid #3b82f6;padding:16px 20px;border-radius:0 12px 12px 0;margin:20px 0"><strong>📐 La théorie de Markowitz</strong><br/>Harry Markowitz a démontré qu\'en combinant des actifs non corrélés, on peut obtenir un portefeuille avec un meilleur rendement ajusté au risque. C\'est le concept de la « frontière efficiente ».</div><h3>Allocation stratégique</h3><p>L\'allocation d\'actifs détermine ~90% de la performance de votre portefeuille. Exemple d\'allocation équilibrée :</p><p>• 60% Actions (croissance)<br/>• 25% Obligations (stabilité)<br/>• 10% Immobilier (revenus)<br/>• 5% Or/Crypto (couverture)</p>',en:'<h2>Building a solid portfolio</h2><p>Portfolio construction is the art of combining different assets to optimize the risk/return ratio.</p>'}},
      { id:'inv-04', title:{fr:'ETFs et gestion passive',en:'ETFs and Passive Management'},
        content:{fr:'<h2>Les ETFs : la révolution de l\'investissement</h2><p>Les ETFs (Exchange-Traded Funds) sont des fonds indiciels cotés en bourse qui répliquent la performance d\'un indice.</p><img src="https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&h=350&fit=crop&q=80" alt="ETFs" style="width:100%;border-radius:12px;margin:20px 0"/><h3>Pourquoi les ETFs ?</h3><p>• <strong>Frais ultra-bas</strong> : 0.03% à 0.5% vs 1-2% pour les fonds actifs<br/>• <strong>Diversification instantanée</strong> : Un seul ETF = des centaines d\'actions<br/>• <strong>Transparence</strong> : Vous savez exactement ce que vous détenez<br/>• <strong>Liquidité</strong> : Achetable/vendable en bourse comme une action</p><div style="background:#fef3c7;border-left:4px solid #f59e0b;padding:16px 20px;border-radius:0 12px 12px 0;margin:20px 0"><strong>⚡ Le saviez-vous ?</strong><br/>Warren Buffett a recommandé à sa famille d\'investir 90% de leur héritage dans un simple ETF S&P 500. Sur 15 ans, les ETFs battent ~85% des gérants professionnels.</div>',en:'<h2>ETFs: the investment revolution</h2><p>ETFs are exchange-traded funds that replicate the performance of an index.</p>'}},
      { id:'inv-05', title:{fr:'Gestion active vs passive',en:'Active vs Passive Management'},
        content:{fr:'<h2>Gestion active vs passive</h2><p>Le grand débat de l\'investissement moderne : faut-il essayer de battre le marché ou simplement le suivre ?</p><h3>Gestion passive</h3><p>Investir dans des ETFs qui répliquent un indice. Frais bas, performance proche du marché. C\'est la stratégie recommandée pour 90% des investisseurs.</p><h3>Gestion active</h3><p>Sélectionner individuellement des titres pour battre le marché. Nécessite du temps, des compétences et accepter des frais plus élevés.</p>',en:'<h2>Active vs passive management</h2><p>The great debate of modern investing.</p>'}},
      { id:'inv-06', title:{fr:'Les frais et leur impact',en:'Fees and Their Impact'},
        content:{fr:'<h2>L\'ennemi silencieux : les frais</h2><p>Les frais d\'investissement peuvent détruire vos rendements sur le long terme. Comprendre et minimiser les frais est crucial.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;padding:16px 20px;border-radius:0 12px 12px 0;margin:20px 0"><strong>🚨 Impact des frais sur 30 ans</strong><br/>100 000€ investis à 8% brut :<br/>• Avec 0.2% de frais → 936 000€<br/>• Avec 2.0% de frais → 574 000€<br/><strong>Différence : 362 000€ perdus en frais !</strong></div>',en:'<h2>The silent killer: fees</h2><p>Investment fees can destroy returns over the long term.</p>'}},
      { id:'inv-07', title:{fr:'Stratégies d\'investissement',en:'Investment Strategies'},
        content:{fr:'<h2>Les grandes stratégies d\'investissement</h2><p>DCA, Value Investing, Growth Investing, Income Investing... Chaque stratégie a ses forces et faiblesses.</p><h3>Dollar Cost Averaging (DCA)</h3><p>Investir un montant fixe à intervalles réguliers. Simple, efficace, et réduit l\'impact de la volatilité.</p><h3>Value Investing</h3><p>Acheter des actions sous-évaluées par rapport à leur valeur intrinsèque. La philosophie de Warren Buffett.</p>',en:'<h2>Major investment strategies</h2><p>DCA, Value, Growth, Income...</p>'}},
      { id:'inv-08', title:{fr:'Analyse macroéconomique',en:'Macroeconomic Analysis'},
        content:{fr:'<h2>Comprendre l\'environnement macro</h2><p>Les marchés financiers sont profondément influencés par l\'environnement macroéconomique : taux d\'intérêt, inflation, croissance du PIB, politique monétaire.</p><h3>Les indicateurs clés</h3><p>• <strong>PIB</strong> : Mesure de la production économique<br/>• <strong>Inflation (CPI)</strong> : Hausse générale des prix<br/>• <strong>Taux directeurs</strong> : Décisions des banques centrales<br/>• <strong>Chômage</strong> : Santé du marché du travail</p>',en:'<h2>Understanding the macro environment</h2><p>Markets are deeply influenced by macroeconomic conditions.</p>'}}
    ]
  },
  trading: {
    modules: [
      { id:'trd-01', title:{fr:'Introduction au trading',en:'Introduction to Trading'},
        content:{fr:'<h2>Le Trading : Art et Science</h2><p>Le trading consiste à acheter et vendre des actifs financiers sur des périodes courtes pour profiter des variations de prix.</p><img src="https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=350&fit=crop&q=80" alt="Trading" style="width:100%;border-radius:12px;margin:20px 0"/><h3>Trading vs Investissement</h3><p>L\'investisseur pense en années, le trader pense en minutes, heures ou jours. Les deux approches sont valides mais nécessitent des compétences différentes.</p><div style="background:#f0fdf4;border-left:4px solid #59A52C;padding:16px 20px;border-radius:0 12px 12px 0;margin:20px 0"><strong>⚠️ Avertissement</strong><br/>Le trading comporte des risques significatifs. Environ 70-80% des traders particuliers perdent de l\'argent. Formez-vous avant de risquer du capital réel.</div><h3>Les types de trading</h3><p>• <strong>Scalping</strong> : Trades de quelques secondes/minutes<br/>• <strong>Day Trading</strong> : Positions ouvertes et fermées dans la journée<br/>• <strong>Swing Trading</strong> : Positions de quelques jours à semaines<br/>• <strong>Position Trading</strong> : Semaines à mois</p>',en:'<h2>Trading: Art and Science</h2><p>Trading involves buying and selling financial assets over short periods to profit from price movements.</p>'}},
      { id:'trd-02', title:{fr:'Chandeliers japonais',en:'Japanese Candlesticks'},
        content:{fr:'<h2>Lire les chandeliers japonais</h2><p>Les chandeliers japonais sont la méthode la plus populaire pour visualiser l\'évolution des prix.</p><img src="https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&h=350&fit=crop&q=80" alt="Chandeliers" style="width:100%;border-radius:12px;margin:20px 0"/><h3>Anatomie d\'un chandelier</h3><p>Chaque chandelier montre 4 informations : <strong>Ouverture, Plus Haut, Plus Bas, Clôture (OHLC)</strong>.</p><p>• <strong>Corps vert/blanc</strong> : Clôture > Ouverture (haussier)<br/>• <strong>Corps rouge/noir</strong> : Clôture < Ouverture (baissier)<br/>• <strong>Mèches</strong> : Indiquent les extrêmes de la période</p><h3>Patterns importants</h3><p>• <strong>Doji</strong> : Indécision du marché<br/>• <strong>Marteau</strong> : Signal de retournement haussier<br/>• <strong>Étoile filante</strong> : Signal de retournement baissier<br/>• <strong>Englobante haussière/baissière</strong> : Forte conviction</p>',en:'<h2>Reading Japanese candlesticks</h2><p>Japanese candlesticks are the most popular way to visualize price action.</p>'}},
      { id:'trd-03', title:{fr:'Price Action',en:'Price Action'},
        content:{fr:'<h2>Le Price Action</h2><p>Le price action est l\'étude du mouvement des prix « nus », sans indicateurs techniques. C\'est la base de toute analyse technique.</p><h3>Supports et Résistances</h3><p>Les niveaux de support et résistance sont les zones où le prix a tendance à s\'arrêter et à inverser sa direction.</p><h3>Tendances</h3><p>• <strong>Tendance haussière</strong> : Séquence de plus hauts et plus bas ascendants<br/>• <strong>Tendance baissière</strong> : Séquence de plus hauts et plus bas descendants<br/>• <strong>Range</strong> : Prix oscillant entre un support et une résistance</p>',en:'<h2>Price Action</h2><p>Price action is studying raw price movement without technical indicators.</p>'}},
      { id:'trd-04', title:{fr:'Indicateurs techniques',en:'Technical Indicators'},
        content:{fr:'<h2>Les indicateurs techniques essentiels</h2><p>Les indicateurs techniques transforment les données de prix en signaux d\'achat ou de vente.</p><h3>Moyennes mobiles (MA)</h3><p>Lissent le prix pour identifier la tendance. La SMA 200 est la plus suivie sur les marchés.</p><h3>RSI (Relative Strength Index)</h3><p>Oscille entre 0 et 100. Au-dessus de 70 = suracheté, en dessous de 30 = survendu.</p><h3>MACD</h3><p>Mesure la convergence/divergence de deux moyennes mobiles. Excellent pour identifier les changements de momentum.</p>',en:'<h2>Essential technical indicators</h2><p>Technical indicators transform price data into buy/sell signals.</p>'}},
      { id:'trd-05', title:{fr:'Stratégies de trading',en:'Trading Strategies'},
        content:{fr:'<h2>Stratégies de trading professionnelles</h2><p>Une stratégie de trading définit quand entrer, quand sortir, et combien risquer.</p><h3>Breakout Trading</h3><p>Entrer quand le prix casse un niveau clé de support/résistance avec du volume.</p><h3>Trend Following</h3><p>Suivre la tendance en utilisant les moyennes mobiles et le momentum.</p>',en:'<h2>Professional trading strategies</h2><p>A trading strategy defines when to enter, exit, and how much to risk.</p>'}},
      { id:'trd-06', title:{fr:'Gestion du risque',en:'Risk Management'},
        content:{fr:'<h2>La gestion du risque : clé de la survie</h2><p>La gestion du risque est ce qui sépare les traders rentables des perdants. Sans elle, même la meilleure stratégie échouera.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;padding:16px 20px;border-radius:0 12px 12px 0;margin:20px 0"><strong>🎯 Règle du 1%</strong><br/>Ne risquez jamais plus de 1-2% de votre capital total sur un seul trade. Avec 10 000€, votre perte maximale par trade devrait être de 100-200€.</div><h3>Ratio Risk/Reward</h3><p>Visez toujours un ratio minimum de 1:2. Si vous risquez 100€, votre objectif de gain devrait être d\'au moins 200€.</p>',en:'<h2>Risk management: the key to survival</h2><p>Risk management separates profitable from losing traders.</p>'}},
      { id:'trd-07', title:{fr:'Psychologie du trading',en:'Trading Psychology'},
        content:{fr:'<h2>La psychologie du trader</h2><p>Le plus grand ennemi du trader, c\'est lui-même. La peur, l\'avidité et l\'égo sont les trois émotions destructrices.</p><h3>Les biais cognitifs</h3><p>• <strong>FOMO</strong> : Fear Of Missing Out — entrer trop tard<br/>• <strong>Biais de confirmation</strong> : Ne voir que ce qui confirme notre opinion<br/>• <strong>Aversion à la perte</strong> : Couper les gains trop tôt, laisser courir les pertes</p>',en:'<h2>Trading psychology</h2><p>Your biggest enemy as a trader is yourself.</p>'}}
    ]
  },
  fundamental: {
    modules: [
      { id:'fun-01', title:{fr:'Introduction à l\'analyse fondamentale',en:'Introduction to Fundamental Analysis'},
        content:{fr:'<h2>L\'analyse fondamentale</h2><p>L\'analyse fondamentale évalue la valeur intrinsèque d\'un actif en étudiant les facteurs économiques, financiers et qualitatifs.</p><img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=350&fit=crop&q=80" alt="Analyse" style="width:100%;border-radius:12px;margin:20px 0"/><h3>Différence avec l\'analyse technique</h3><p>L\'analyse technique étudie les graphiques de prix. L\'analyse fondamentale étudie les causes derrière les mouvements de prix : résultats financiers, conditions économiques, gouvernance.</p><div style="background:#f0fdf4;border-left:4px solid #59A52C;padding:16px 20px;border-radius:0 12px 12px 0;margin:20px 0"><strong>💡 Conseil</strong><br/>Les meilleurs investisseurs combinent analyse fondamentale et technique. L\'une vous dit QUOI acheter, l\'autre QUAND.</div>',en:'<h2>Fundamental Analysis</h2><p>Fundamental analysis evaluates the intrinsic value of an asset by studying economic, financial and qualitative factors.</p>'}},
      { id:'fun-02', title:{fr:'Lecture des bilans financiers',en:'Reading Financial Statements'},
        content:{fr:'<h2>Comprendre les états financiers</h2><p>Les trois états financiers essentiels sont le bilan, le compte de résultat et le tableau des flux de trésorerie.</p><h3>Le Bilan</h3><p>Photo instantanée de ce que l\'entreprise possède (actifs) et doit (passifs).</p><h3>Le Compte de Résultat</h3><p>Film de la performance sur une période : revenus - charges = bénéfice net.</p><h3>Ratios clés</h3><p>• <strong>PER (Price/Earnings)</strong> : Combien vous payez par euro de bénéfice<br/>• <strong>ROE (Return on Equity)</strong> : Rentabilité des capitaux propres<br/>• <strong>Dette/EBITDA</strong> : Niveau d\'endettement</p>',en:'<h2>Understanding financial statements</h2><p>The three essential statements are balance sheet, income statement, and cash flow statement.</p>'}},
      { id:'fun-03', title:{fr:'Politique monétaire',en:'Monetary Policy'},
        content:{fr:'<h2>La politique monétaire et ses impacts</h2><p>Les banques centrales (BCE, FED, BoJ) contrôlent la masse monétaire et les taux d\'intérêt, influençant directement les marchés.</p><h3>Taux directeurs</h3><p>Quand la BCE baisse les taux → l\'argent est moins cher → les marchés montent généralement. Et inversement.</p><h3>Quantitative Easing (QE)</h3><p>La banque centrale achète des obligations pour injecter de la liquidité. C\'est l\'arme ultime en période de crise.</p>',en:'<h2>Monetary policy and its impacts</h2><p>Central banks control money supply and interest rates.</p>'}},
      { id:'fun-04', title:{fr:'Indicateurs macroéconomiques',en:'Macroeconomic Indicators'},
        content:{fr:'<h2>Les indicateurs macro à surveiller</h2><p>Ces données économiques font bouger les marchés. Savoir les interpréter est un avantage compétitif.</p><h3>Calendrier économique</h3><p>• <strong>NFP (Non-Farm Payrolls)</strong> : Premier vendredi du mois, emploi US<br/>• <strong>CPI (Inflation)</strong> : Milieu de mois<br/>• <strong>Décisions taux FED/BCE</strong> : 8 fois par an<br/>• <strong>PIB</strong> : Trimestriel</p>',en:'<h2>Key macro indicators</h2><p>Economic data that moves markets.</p>'}},
      { id:'fun-05', title:{fr:'Valorisation d\'entreprise',en:'Company Valuation'},
        content:{fr:'<h2>Méthodes de valorisation</h2><p>Comment déterminer si une action est surévaluée ou sous-évaluée ?</p><h3>DCF (Discounted Cash Flow)</h3><p>Projeter les flux de trésorerie futurs et les ramener en valeur présente. C\'est la méthode la plus rigoureuse mais aussi la plus complexe.</p><h3>Comparaison par multiples</h3><p>Comparer le PER, EV/EBITDA, P/B d\'une entreprise avec ses pairs du même secteur.</p>',en:'<h2>Valuation methods</h2><p>How to determine if a stock is over or undervalued.</p>'}},
      { id:'fun-06', title:{fr:'Géopolitique et marchés',en:'Geopolitics and Markets'},
        content:{fr:'<h2>L\'impact géopolitique sur les marchés</h2><p>Guerres commerciales, sanctions, tensions internationales... La géopolitique peut provoquer des mouvements violents sur les marchés.</p><h3>Exemples historiques</h3><p>• <strong>2022</strong> : Guerre Ukraine → Envolée des prix de l\'énergie<br/>• <strong>2018-2020</strong> : Guerre commerciale US-Chine → Volatilité accrue<br/>• <strong>2020</strong> : Covid-19 → Krach puis recovery record</p>',en:'<h2>Geopolitical impact on markets</h2><p>Trade wars, sanctions, international tensions move markets.</p>'}}
    ]
  },
  simulator: { modules: [] }
};
